create database foodorder;

use foodorder;

create table foodorder (order_id  int primary key , --primary key
order_name varchar(150)not null ,
order_price varchar(150) not null ,
city varchar(150),
address varchar(500)
);

insert into foodorder(order_id,order_name, order_price,city,address)
value (58,'burger', 250,'pune','kothrud');

select * from foodorder;

update address set city 'pune'
where order_id = 1;


insert into foodorder (order_id, order_name, order_price, city, address) values (1, 'Rhiamon', 'Loghan', 'Wieczfnia KoÅ›cielna', '5th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (2, 'Elisabet', 'Glisenan', 'Labney', 'Room 1801');
insert into foodorder (order_id, order_name, order_price, city, address) values (3, 'Burtie', 'Woolerton', 'Lianhe', '13th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (4, 'Bianka', 'Le Grice', 'Chengbei', 'PO Box 5222');
insert into foodorder (order_id, order_name, order_price, city, address) values (5, 'Aprilette', 'Frazier', 'Chaihe', 'PO Box 10614');
insert into foodorder (order_id, order_name, order_price, city, address) values (6, 'Ivar', 'Alibone', 'Arkalyk', 'PO Box 24582');
insert into foodorder (order_id, order_name, order_price, city, address) values (7, 'Abbott', 'Uman', 'Santa Cruz De Tenerife', '3rd Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (8, 'Sunshine', 'Marzellano', 'Baliuag', 'Suite 44');
insert into foodorder (order_id, order_name, order_price, city, address) values (9, 'Minnnie', 'Shackelton', 'Bagacay', 'Suite 92');
insert into foodorder (order_id, order_name, order_price, city, address) values (10, 'Finn', 'Weyland', 'Beaverton', 'Room 1540');
insert into foodorder (order_id, order_name, order_price, city, address) values (11, 'Skye', 'Heading', 'Åubniany', 'PO Box 83531');
insert into foodorder (order_id, order_name, order_price, city, address) values (12, 'Jonie', 'Forlonge', 'Orsay', '7th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (13, 'Babs', 'Nassy', 'Dongle', 'Suite 36');
insert into foodorder (order_id, order_name, order_price, city, address) values (14, 'Brockie', 'Binne', 'Escuintla', 'Suite 46');
insert into foodorder (order_id, order_name, order_price, city, address) values (15, 'Raleigh', 'Brignell', 'Kedrovyy', 'Suite 50');
insert into foodorder (order_id, order_name, order_price, city, address) values (16, 'Vivyan', 'Blunsom', 'Plumbon', 'Room 179');
insert into foodorder (order_id, order_name, order_price, city, address) values (17, 'Kial', 'Liggins', 'Laweueng', 'PO Box 61418');
insert into foodorder (order_id, order_name, order_price, city, address) values (18, 'Viki', 'Buckingham', 'KonÃ«vo', 'Room 1618');
insert into foodorder (order_id, order_name, order_price, city, address) values (19, 'Arden', 'Cowlin', 'Seremban', 'Apt 988');
insert into foodorder (order_id, order_name, order_price, city, address) values (20, 'Ky', 'Wykey', 'Mopti', '10th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (21, 'Jan', 'Danielsohn', 'ItanhaÃ©m', 'Apt 1898');
insert into foodorder (order_id, order_name, order_price, city, address) values (22, 'Karina', 'Pointer', 'Tvrdonice', '5th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (23, 'Nathalie', 'Mandal', 'Crespo', 'Suite 47');
insert into foodorder (order_id, order_name, order_price, city, address) values (24, 'Vevay', 'Byneth', 'AianÃ­', '6th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (25, 'Cal', 'Slaughter', 'Idah', 'Suite 47');
insert into foodorder (order_id, order_name, order_price, city, address) values (26, 'Marcelo', 'Kelloch', 'Pengwan', 'Apt 53');
insert into foodorder (order_id, order_name, order_price, city, address) values (27, 'Daisi', 'Tidd', 'Horrom', 'Room 360');
insert into foodorder (order_id, order_name, order_price, city, address) values (28, 'Gunther', 'Berthod', 'Iitti', 'Suite 86');
insert into foodorder (order_id, order_name, order_price, city, address) values (29, 'Lynna', 'Phettis', 'Zhajin', 'Room 397');
insert into foodorder (order_id, order_name, order_price, city, address) values (30, 'Emilia', 'Crosier', 'Saint-PÃ©ray', 'Apt 256');
insert into foodorder (order_id, order_name, order_price, city, address) values (31, 'Leann', 'Chartres', 'Huáº¿', '12th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (32, 'Roderic', 'McFeate', 'Hor', '3rd Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (33, 'Lanae', 'Varey', 'ChÆ° PrÃ´ng', 'PO Box 65299');
insert into foodorder (order_id, order_name, order_price, city, address) values (34, 'Ruben', 'Stoile', 'Aparecida', 'Room 860');
insert into foodorder (order_id, order_name, order_price, city, address) values (35, 'Sharia', 'Cometto', 'Santo AdriÃ£o Vizela', 'Apt 795');
insert into foodorder (order_id, order_name, order_price, city, address) values (36, 'Jacintha', 'Sibary', 'Wuma', '20th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (37, 'Kinnie', 'Wilfing', 'Zambujal', 'Apt 969');
insert into foodorder (order_id, order_name, order_price, city, address) values (38, 'Norbert', 'Swindles', 'Cihe', 'Suite 41');
insert into foodorder (order_id, order_name, order_price, city, address) values (39, 'Skippy', 'Huyton', 'Solna', 'Apt 58');
insert into foodorder (order_id, order_name, order_price, city, address) values (40, 'Ulrick', 'Gelderd', 'Sajia', 'Apt 85');
insert into foodorder (order_id, order_name, order_price, city, address) values (41, 'Pauly', 'Rough', 'Montague', 'PO Box 21639');
insert into foodorder (order_id, order_name, order_price, city, address) values (42, 'Aguie', 'Losano', 'Pasirpengarayan', 'PO Box 61324');
insert into foodorder (order_id, order_name, order_price, city, address) values (43, 'Ayn', 'Hadenton', 'Massaguet', '15th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (44, 'Florrie', 'Oddie', 'Viana', 'Apt 1468');
insert into foodorder (order_id, order_name, order_price, city, address) values (45, 'Gigi', 'Sallery', 'YÅnggwang-Å­p', 'PO Box 27125');
insert into foodorder (order_id, order_name, order_price, city, address) values (46, 'Brunhilde', 'Tullis', 'Puerto Cisnes', '14th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (47, 'Klarika', 'Tight', 'Port Nolloth', 'PO Box 30074');
insert into foodorder (order_id, order_name, order_price, city, address) values (48, 'Becca', 'Heitz', 'Arrah', 'Apt 274');
insert into foodorder (order_id, order_name, order_price, city, address) values (49, 'Karena', 'Deery', 'Andong', '20th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (50, 'Logan', 'Jeaffreson', 'Puyang', 'Suite 63');
insert into foodorder (order_id, order_name, order_price, city, address) values (51, 'Launce', 'Janicki', 'Gaoshibei', 'Suite 52');
insert into foodorder (order_id, order_name, order_price, city, address) values (52, 'Tamarah', 'Hinchcliffe', 'PelÃ³pion', '18th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (53, 'Boyce', 'Millwall', 'Strasbourg', 'PO Box 71060');
insert into foodorder (order_id, order_name, order_price, city, address) values (54, 'Margarete', 'Neylon', 'Budakovo', 'Suite 67');
insert into foodorder (order_id, order_name, order_price, city, address) values (55, 'Adela', 'Ashlin', 'QarqÄ«n', '12th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (56, 'Anastasie', 'Whiten', 'Charlestown', 'PO Box 93671');
insert into foodorder (order_id, order_name, order_price, city, address) values (57, 'Misty', 'Totterdill', 'Baiguan', 'Apt 1779');
insert into foodorder (order_id, order_name, order_price, city, address) values (58, 'Merwin', 'Kensett', 'Dongtucheng', 'Apt 778');
insert into foodorder (order_id, order_name, order_price, city, address) values (59, 'Pat', 'Ciccarello', 'Mempawah', 'Suite 99');
insert into foodorder (order_id, order_name, order_price, city, address) values (60, 'Alyse', 'McCrory', 'Lindavista', 'Suite 53');
insert into foodorder (order_id, order_name, order_price, city, address) values (61, 'Sherye', 'Desmond', 'Karanganyar', '4th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (62, 'Molly', 'Kittow', 'Dalong', 'Room 326');
insert into foodorder (order_id, order_name, order_price, city, address) values (63, 'Breanne', 'Bance', 'Fos-sur-Mer', '17th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (64, 'Dorothy', 'de Savery', 'HornÃ­ JiÅ™etÃ­n', 'Apt 1908');
insert into foodorder (order_id, order_name, order_price, city, address) values (65, 'Janella', 'Hulstrom', 'Luofang', 'Room 790');
insert into foodorder (order_id, order_name, order_price, city, address) values (66, 'Sky', 'Klulicek', 'Pedro II', '20th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (67, 'Crissie', 'Roarty', 'Taphan Hin', 'Room 1355');
insert into foodorder (order_id, order_name, order_price, city, address) values (68, 'Zerk', 'Gillbee', 'Septfontaines', 'Suite 61');
insert into foodorder (order_id, order_name, order_price, city, address) values (69, 'Horatius', 'Bannell', 'Lerrnanist', 'PO Box 7847');
insert into foodorder (order_id, order_name, order_price, city, address) values (70, 'Louella', 'Cockrill', 'Dongyang', 'Apt 1000');
insert into foodorder (order_id, order_name, order_price, city, address) values (71, 'Angie', 'Burnes', 'Oslo', 'Room 1329');
insert into foodorder (order_id, order_name, order_price, city, address) values (72, 'Bradley', 'Briers', 'Sipoholon', 'Apt 1602');
insert into foodorder (order_id, order_name, order_price, city, address) values (73, 'Bil', 'Malser', 'Tenja', '5th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (74, 'Diandra', 'Meaker', 'Saint Augustine', 'PO Box 47657');
insert into foodorder (order_id, order_name, order_price, city, address) values (75, 'Christabella', 'Trenouth', 'Å½amberk', 'Room 1503');
insert into foodorder (order_id, order_name, order_price, city, address) values (76, 'Cesya', 'Galey', 'Liangshan', 'Apt 321');
insert into foodorder (order_id, order_name, order_price, city, address) values (77, 'Pavla', 'Gillcrist', 'Toyohashi', '2nd Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (78, 'Jo-ann', 'Jeannequin', 'MonjarÃ¡s', 'Room 677');
insert into foodorder (order_id, order_name, order_price, city, address) values (79, 'Yettie', 'Wagg', 'Mrzezino', 'Room 592');
insert into foodorder (order_id, order_name, order_price, city, address) values (80, 'Lelia', 'Skelhorn', 'Youshan', 'Room 773');
insert into foodorder (order_id, order_name, order_price, city, address) values (81, 'Maximilian', 'Rutigliano', 'Montpellier', 'Apt 1880');
insert into foodorder (order_id, order_name, order_price, city, address) values (82, 'Casper', 'Halburton', 'CuiabÃ¡', 'PO Box 73500');
insert into foodorder (order_id, order_name, order_price, city, address) values (83, 'Kenton', 'Zmitrovich', 'Wuluo', 'Room 795');
insert into foodorder (order_id, order_name, order_price, city, address) values (84, 'Kellie', 'Measham', 'Shazi', 'Room 340');
insert into foodorder (order_id, order_name, order_price, city, address) values (85, 'Hattie', 'Torbett', 'JÃµhvi', 'Room 411');
insert into foodorder (order_id, order_name, order_price, city, address) values (86, 'Lesli', 'Portal', 'Luoyang', '1st Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (87, 'Margret', 'Finci', 'Legok', 'Apt 1269');
insert into foodorder (order_id, order_name, order_price, city, address) values (88, 'Mersey', 'Cucinotta', 'Tambir', 'PO Box 85882');
insert into foodorder (order_id, order_name, order_price, city, address) values (89, 'Carleen', 'Runnicles', 'Maji', '17th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (90, 'Kerk', 'Seed', 'ChigorÃ©', 'Room 7');
insert into foodorder (order_id, order_name, order_price, city, address) values (91, 'Stanwood', 'Kerbler', 'Karangbalong', 'Suite 13');
insert into foodorder (order_id, order_name, order_price, city, address) values (92, 'Allie', 'Pena', 'KÃ¸benhavn', 'Apt 1210');
insert into foodorder (order_id, order_name, order_price, city, address) values (93, 'Theo', 'Casella', 'Masons Bay', 'PO Box 76745');
insert into foodorder (order_id, order_name, order_price, city, address) values (94, 'Starlene', 'Aronin', 'Wushi', 'Room 775');
insert into foodorder (order_id, order_name, order_price, city, address) values (95, 'Oriana', 'Oake', 'Qalâ€˜at BÄ«shah', 'Apt 542');
insert into foodorder (order_id, order_name, order_price, city, address) values (96, 'Sisely', 'Pepi', 'Adelaide', 'PO Box 56955');
insert into foodorder (order_id, order_name, order_price, city, address) values (97, 'Lion', 'Mazzia', 'Hagfors', 'PO Box 8500');
insert into foodorder (order_id, order_name, order_price, city, address) values (98, 'Isiahi', 'Darco', 'Kabarnet', 'Room 96');
insert into foodorder (order_id, order_name, order_price, city, address) values (99, 'Elyssa', 'Lithgow', 'Valmiera', 'PO Box 87304');
insert into foodorder (order_id, order_name, order_price, city, address) values (100, 'Brenden', 'Quadri', 'Yangsan', 'Suite 77');
insert into foodorder (order_id, order_name, order_price, city, address) values (101, 'Lucky', 'Campany', 'Vyzhnytsya', 'Apt 821');
insert into foodorder (order_id, order_name, order_price, city, address) values (102, 'Lonny', 'Stilly', 'Paracambi', '17th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (103, 'Barnie', 'Clowley', 'New Haven', 'Room 40');
insert into foodorder (order_id, order_name, order_price, city, address) values (104, 'Erma', 'Prantoni', 'Orlovskiy', 'PO Box 41985');
insert into foodorder (order_id, order_name, order_price, city, address) values (105, 'Anica', 'Sute', 'Orzesze', 'Apt 896');
insert into foodorder (order_id, order_name, order_price, city, address) values (106, 'Hugh', 'Redholls', 'Hetang', 'Apt 1127');
insert into foodorder (order_id, order_name, order_price, city, address) values (107, 'Ingaberg', 'Winkett', 'Stalbe', 'Suite 41');
insert into foodorder (order_id, order_name, order_price, city, address) values (108, 'Hamlen', 'Pinard', 'Santander', 'Apt 1123');
insert into foodorder (order_id, order_name, order_price, city, address) values (109, 'Keely', 'Barhims', 'Saint-Louis', '8th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (110, 'Ravi', 'Drinkall', 'Hubei', 'Apt 1607');
insert into foodorder (order_id, order_name, order_price, city, address) values (111, 'Ange', 'Tennewell', 'Baiyan', '1st Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (112, 'Clerissa', 'Irons', 'Pajung', '2nd Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (113, 'Arlana', 'Glaum', 'Emmen', '11th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (114, 'Kristan', 'Roles', 'Daping', '19th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (115, 'Arda', 'Dofty', 'San Antonio', 'PO Box 12322');
insert into foodorder (order_id, order_name, order_price, city, address) values (116, 'Correy', 'Gronw', 'Marneuli', 'Room 395');
insert into foodorder (order_id, order_name, order_price, city, address) values (117, 'Paten', 'Marzello', 'Fatukanutu', 'Room 1387');
insert into foodorder (order_id, order_name, order_price, city, address) values (118, 'Garv', 'Laurenson', 'Kalengwa', 'PO Box 57756');
insert into foodorder (order_id, order_name, order_price, city, address) values (119, 'Katine', 'McCallion', 'Batulenger Barat', '19th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (120, 'Goldia', 'Uttley', 'Xiluodu', 'Room 441');
insert into foodorder (order_id, order_name, order_price, city, address) values (121, 'Karlan', 'Costain', 'Liangguang', 'Room 1883');
insert into foodorder (order_id, order_name, order_price, city, address) values (122, 'Faber', 'Fibbens', 'Cibenda', 'PO Box 54196');
insert into foodorder (order_id, order_name, order_price, city, address) values (123, 'Constantia', 'Letessier', 'BelÃ©n de los AndaquÃ­es', 'PO Box 56865');
insert into foodorder (order_id, order_name, order_price, city, address) values (124, 'Imelda', 'Lanfer', 'Karlskrona', 'PO Box 37482');
insert into foodorder (order_id, order_name, order_price, city, address) values (125, 'Michel', 'Dobson', 'Boniewo', 'Room 815');
insert into foodorder (order_id, order_name, order_price, city, address) values (126, 'Rana', 'Bonnesen', 'Ãgua Retorta', 'Apt 1642');
insert into foodorder (order_id, order_name, order_price, city, address) values (127, 'Kaylil', 'Yushkov', 'Owo', 'Apt 319');
insert into foodorder (order_id, order_name, order_price, city, address) values (128, 'Revkah', 'Ainsley', 'Nkongsamba', 'Room 921');
insert into foodorder (order_id, order_name, order_price, city, address) values (129, 'Vivianna', 'Khadir', 'Kuala Belait', '19th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (130, 'Delcine', 'Gudd', 'Abakaliki', 'Apt 1907');
insert into foodorder (order_id, order_name, order_price, city, address) values (131, 'Cherri', 'Tomlinson', 'Cernache do Bonjardim', '12th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (132, 'Alphard', 'Kornacki', 'Cela', 'Suite 65');
insert into foodorder (order_id, order_name, order_price, city, address) values (133, 'Kerrie', 'List', 'Sanlidian', 'Room 843');
insert into foodorder (order_id, order_name, order_price, city, address) values (134, 'Eirena', 'Sterland', 'Zhanping', '16th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (135, 'Anneliese', 'Keeltagh', 'TuroÅ›Å„ KoÅ›cielna', 'PO Box 83075');
insert into foodorder (order_id, order_name, order_price, city, address) values (136, 'Agneta', 'McAvinchey', 'Mirovka', '2nd Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (137, 'Arri', 'Rubenchik', 'Trat', 'Room 1837');
insert into foodorder (order_id, order_name, order_price, city, address) values (138, 'Asa', 'Trinkwon', 'Kashin', 'Suite 34');
insert into foodorder (order_id, order_name, order_price, city, address) values (139, 'Sander', 'Corbet', 'Kristiansund N', '4th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (140, 'Gianni', 'O''Mullally', 'Masaran', 'Room 499');
insert into foodorder (order_id, order_name, order_price, city, address) values (141, 'Jayme', 'Robichon', 'Miaoshi', 'PO Box 18133');
insert into foodorder (order_id, order_name, order_price, city, address) values (142, 'Babs', 'Spinney', 'Port Moody', 'Room 34');
insert into foodorder (order_id, order_name, order_price, city, address) values (143, 'Raddy', 'Shackleford', 'La Salud', '5th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (144, 'Augustina', 'Folbigg', 'Sandviken', 'PO Box 40429');
insert into foodorder (order_id, order_name, order_price, city, address) values (145, 'Alain', 'Serjeant', 'Morcellemont Saint AndrÃ©', '14th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (146, 'Terrell', 'Bauer', 'Pulilan', 'PO Box 4645');
insert into foodorder (order_id, order_name, order_price, city, address) values (147, 'Madison', 'Duddell', 'GuÃ©rande', 'Suite 74');
insert into foodorder (order_id, order_name, order_price, city, address) values (148, 'Aryn', 'Drennan', 'Puerto QuellÃ³n', '3rd Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (149, 'Elli', 'Last', 'Lasek', '6th Floor');
insert into foodorder (order_id, order_name, order_price, city, address) values (150, 'Ailbert', 'Rudledge', 'Mantang', 'Room 357');
insert into foodorder (order_id, order_name, order_price, city, address) values (151, 'Nedda', 'Nisby', 'Fanrong', 'Room 746');
insert into foodorder (order_id, order_name, order_price, city, address) values (152, 'Lula', 'Pirolini', 'San Francisco', 'PO Box 70753');
insert into foodorder (order_id, order_name, order_price, city, address) values (153, 'Carolan', 'Summers', 'Kotli LohÄrÄn', 'Apt 1754');
insert into foodorder (order_id, order_name, order_price, city, address) values (154, 'Stormy', 'Mylchreest', 'Ã…storp', 'Room 1242');
insert into foodorder (order_id, order_name, order_price, city, address) values (155, 'Hillary', 'Shucksmith', 'Santo Domingo', 'Room 421');
insert into foodorder (order_id, order_name, order_price, city, address) values (156, 'Glenna', 'Lammin', 'Kamyshin', 'Apt 1017');
insert into foodorder (order_id, order_name, order_price, city, address) values (157, 'Riki', 'Satyford', 'Fukui-shi', 'Suite 58');
